import 'package:flutter/material.dart';
import 'package:flutterapp/ui_designapp/generatedkeranjangsayawidget/generated/GeneratedFrame5Widget3.dart';
import 'package:flutterapp/ui_designapp/generatedkeranjangsayawidget/generated/GeneratedFrame25Widget.dart';
import 'package:flutterapp/ui_designapp/generatedkeranjangsayawidget/generated/GeneratedFrame24Widget.dart';
import 'package:flutterapp/ui_designapp/generatedkeranjangsayawidget/generated/GeneratedGroup6Widget1.dart';
import 'package:flutterapp/ui_designapp/generatedkeranjangsayawidget/generated/GeneratedFrame8Widget1.dart';
import 'package:flutterapp/ui_designapp/generatedkeranjangsayawidget/generated/GeneratedGroup62Widget1.dart';
import 'package:flutterapp/ui_designapp/generatedkeranjangsayawidget/generated/GeneratedFrame26Widget.dart';
import 'package:flutterapp/ui_designapp/generatedkeranjangsayawidget/generated/GeneratedFrame23Widget.dart';
import 'package:flutterapp/ui_designapp/generatedkeranjangsayawidget/generated/GeneratedFrame22Widget1.dart';
import 'package:flutterapp/ui_designapp/generatedkeranjangsayawidget/generated/GeneratedFrame21Widget.dart';
import 'package:flutterapp/ui_designapp/generatedkeranjangsayawidget/generated/GeneratedGroup20Widget.dart';

/* Frame Keranjang saya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKeranjangsayaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 414.0,
              height: 896.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 400.0,
                      right: null,
                      bottom: null,
                      width: 382.0,
                      height: 42.0,
                      child: GeneratedFrame8Widget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 148.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 100.0,
                      child: GeneratedFrame21Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 250.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 100.0,
                      child: GeneratedFrame22Widget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 352.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 100.0,
                      child: GeneratedFrame23Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 454.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 100.0,
                      child: GeneratedFrame24Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 556.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 100.0,
                      child: GeneratedFrame25Widget(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 835.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 61.0,
              child: GeneratedFrame26Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 832.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 64.0,
              child: GeneratedFrame5Widget3(),
            ),
            Positioned(
              left: 0.0,
              top: 832.0,
              right: null,
              bottom: null,
              width: 0.0,
              height: 0.0,
              child: GeneratedGroup62Widget1(),
            ),
            Positioned(
              left: 0.0,
              top: 112.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 30.0,
              child: GeneratedGroup20Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 112.0,
              child: GeneratedGroup6Widget1(),
            )
          ]),
    ));
  }
}
