import 'package:flutter/material.dart';
import 'package:flutterapp/ui_designapp/generatedprofilewidget/generated/GeneratedFrame28Widget.dart';
import 'package:flutterapp/ui_designapp/generatedprofilewidget/generated/GeneratedFrame15Widget.dart';
import 'package:flutterapp/ui_designapp/generatedprofilewidget/generated/GeneratedGroup6Widget11.dart';
import 'package:flutterapp/ui_designapp/generatedprofilewidget/generated/GeneratedFrame5Widget20.dart';
import 'package:flutterapp/ui_designapp/generatedprofilewidget/generated/GeneratedFrame16Widget.dart';
import 'package:flutterapp/ui_designapp/generatedprofilewidget/generated/GeneratedGroup62Widget11.dart';

/* Frame Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 414.0,
              height: 896.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 112.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 282.0,
                      child: GeneratedFrame15Widget(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 402.0,
                      right: null,
                      bottom: null,
                      width: 382.0,
                      height: 198.0,
                      child: GeneratedFrame16Widget(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 608.0,
                      right: null,
                      bottom: null,
                      width: 382.0,
                      height: 295.0,
                      child: GeneratedFrame28Widget(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 832.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 64.0,
              child: GeneratedFrame5Widget20(),
            ),
            Positioned(
              left: 0.0,
              top: 804.0,
              right: null,
              bottom: null,
              width: 0.0,
              height: 0.0,
              child: GeneratedGroup62Widget11(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 112.0,
              child: GeneratedGroup6Widget11(),
            )
          ]),
    ));
  }
}
