import 'package:flutter/material.dart';
import 'package:flutterapp/ui_designapp/generatedhomepageswidget/generated/GeneratedFrame13Widget1.dart';
import 'package:flutterapp/ui_designapp/generatedhomepageswidget/generated/GeneratedFrame14Widget1.dart';
import 'package:flutterapp/ui_designapp/generatedhomepageswidget/generated/GeneratedGroup6Widget14.dart';
import 'package:flutterapp/ui_designapp/generatedhomepageswidget/generated/GeneratedFrame6Widget1.dart';
import 'package:flutterapp/ui_designapp/generatedhomepageswidget/generated/GeneratedFrame27Widget1.dart';
import 'package:flutterapp/ui_designapp/generatedhomepageswidget/generated/GeneratedGroup8Widget2.dart';
import 'package:flutterapp/ui_designapp/generatedhomepageswidget/generated/GeneratedGroup9Widget2.dart';
import 'package:flutterapp/ui_designapp/generatedhomepageswidget/generated/GeneratedFrame8Widget10.dart';
import 'package:flutterapp/ui_designapp/generatedhomepageswidget/generated/GeneratedFrame5Widget26.dart';
import 'package:flutterapp/ui_designapp/generatedhomepageswidget/generated/GeneratedGroup7Widget2.dart';
import 'package:flutterapp/ui_designapp/generatedhomepageswidget/generated/GeneratedGroup62Widget14.dart';

/* Frame Home Pages
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomePagesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1201.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 414.0,
                            height: 1201.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 393.0,
                                    right: null,
                                    bottom: null,
                                    width: 381.0,
                                    height: 240.0,
                                    child: GeneratedGroup7Widget2(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 647.0,
                                    right: null,
                                    bottom: null,
                                    width: 381.0,
                                    height: 240.0,
                                    child: GeneratedGroup8Widget2(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 901.0,
                                    right: null,
                                    bottom: null,
                                    width: 381.0,
                                    height: 240.0,
                                    child: GeneratedGroup9Widget2(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 378.0,
                                    right: null,
                                    bottom: null,
                                    width: 414.0,
                                    height: 823.0,
                                    child: GeneratedFrame27Widget1(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 400.0,
                                    right: null,
                                    bottom: null,
                                    width: 382.0,
                                    height: 42.0,
                                    child: GeneratedFrame8Widget10(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 112.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 266.0,
              child: GeneratedFrame14Widget1(),
            ),
            Positioned(
              left: 0.0,
              top: 832.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 64.0,
              child: GeneratedFrame5Widget26(),
            ),
            Positioned(
              left: 0.0,
              top: 805.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 92.0,
              child: GeneratedGroup62Widget14(),
            ),
            Positioned(
              left: 16.0,
              top: 288.0,
              right: null,
              bottom: null,
              width: 382.0,
              height: 86.0,
              child: GeneratedFrame13Widget1(),
            ),
            Positioned(
              left: 16.0,
              top: 120.0,
              right: null,
              bottom: null,
              width: 382.0,
              height: 164.0,
              child: GeneratedFrame6Widget1(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 112.0,
              child: GeneratedGroup6Widget14(),
            )
          ]),
    ));
  }
}
