import 'package:flutter/material.dart';

/* Rectangle Screenshot_20211207-140058_MySiskop Adis 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreenshot_20211207140058_MySiskopAdis1Widget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: Container(
        width: 414.0,
        height: 1166.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Image.asset(
            "assets/images/9f84a7d786487b4443eb35d868ef4a983c20df50.png",
            color: null,
            fit: BoxFit.cover,
            width: 414.0,
            height: 1166.0,
            colorBlendMode: BlendMode.dstATop,
          ),
        ),
      ),
    ));
  }
}
