import 'package:flutter/material.dart';
import 'package:flutterapp/ui_designapp/generateddetaildestinasiwidget/generated/GeneratedFrame5Widget13.dart';
import 'package:flutterapp/ui_designapp/generateddetaildestinasiwidget/generated/GeneratedFrame55Widget.dart';
import 'package:flutterapp/ui_designapp/generateddetaildestinasiwidget/generated/GeneratedFrame54Widget.dart';
import 'package:flutterapp/ui_designapp/generateddetaildestinasiwidget/generated/GeneratedGroup6Widget7.dart';

/* Frame Detail Destinasi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDetailDestinasiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1022.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 414.0,
                            height: 1022.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 1.0,
                                    top: 557.0,
                                    right: null,
                                    bottom: null,
                                    width: 414.0,
                                    height: 465.0,
                                    child: GeneratedFrame54Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 113.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 432.0,
              child: GeneratedFrame55Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 832.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 64.0,
              child: GeneratedFrame5Widget13(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 112.0,
              child: GeneratedGroup6Widget7(),
            )
          ]),
    ));
  }
}
