import 'package:flutter/material.dart';
import 'package:flutterapp/ui_designapp/generatedregistrasiuserwidget/generated/GeneratedFrameWidget249.dart';
import 'package:flutterapp/ui_designapp/generatedregistrasiuserwidget/generated/GeneratedGroup62Widget12.dart';
import 'package:flutterapp/ui_designapp/generatedregistrasiuserwidget/generated/GeneratedGroup6Widget12.dart';
import 'package:flutterapp/ui_designapp/generatedregistrasiuserwidget/generated/GeneratedFrame50Widget.dart';
import 'package:flutterapp/ui_designapp/generatedregistrasiuserwidget/generated/GeneratedFrame5Widget22.dart';
import 'package:flutterapp/ui_designapp/generatedregistrasiuserwidget/generated/GeneratedEllipse5Widget.dart';

/* Frame Registrasi User
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegistrasiUserWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 414.0,
              height: 896.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 27.0,
                      top: 209.0,
                      right: null,
                      bottom: null,
                      width: 360.0,
                      height: 480.0,
                      child: GeneratedFrame50Widget(),
                    ),
                    Positioned(
                      left: 142.0,
                      top: 144.0,
                      right: null,
                      bottom: null,
                      width: 130.0,
                      height: 130.0,
                      child: GeneratedEllipse5Widget(),
                    ),
                    Positioned(
                      left: 164.0,
                      top: 166.0,
                      right: null,
                      bottom: null,
                      width: 86.0,
                      height: 86.0,
                      child: GeneratedFrameWidget249(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 832.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 64.0,
              child: GeneratedFrame5Widget22(),
            ),
            Positioned(
              left: 0.0,
              top: 804.0,
              right: null,
              bottom: null,
              width: 0.0,
              height: 0.0,
              child: GeneratedGroup62Widget12(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 112.0,
              child: GeneratedGroup6Widget12(),
            )
          ]),
    ));
  }
}
