import 'package:flutter/material.dart';
import 'package:flutterapp/ui_designapp/generatedbuttomwidget/generated/GeneratedRectangle23Widget.dart';
import 'package:flutterapp/ui_designapp/generatedbuttomwidget/generated/GeneratedButtomWidget1.dart';
import 'package:flutterapp/ui_designapp/generatedbuttomwidget/generated/GeneratedRectangle24Widget.dart';

/* Group Buttom
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedButtomWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: Container(
        width: 0.0,
        height: 0.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 30.0,
                child: GeneratedButtomWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 46.0,
                child: GeneratedRectangle23Widget(),
              ),
              Positioned(
                left: 159.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 46.0,
                child: GeneratedRectangle24Widget(),
              )
            ]),
      ),
    ));
  }
}
