import 'package:flutter/material.dart';
import 'package:flutterapp/ui_designapp/generatednotifikasispwidget/generated/GeneratedFrame48Widget1.dart';
import 'package:flutterapp/ui_designapp/generatednotifikasispwidget/generated/GeneratedFrame47Widget.dart';
import 'package:flutterapp/ui_designapp/generatednotifikasispwidget/generated/GeneratedFrame51Widget.dart';
import 'package:flutterapp/ui_designapp/generatednotifikasispwidget/generated/GeneratedFrame5Widget6.dart';
import 'package:flutterapp/ui_designapp/generatednotifikasispwidget/generated/GeneratedGroup20Widget2.dart';
import 'package:flutterapp/ui_designapp/generatednotifikasispwidget/generated/GeneratedFrame49Widget1.dart';
import 'package:flutterapp/ui_designapp/generatednotifikasispwidget/generated/GeneratedGroup62Widget3.dart';
import 'package:flutterapp/ui_designapp/generatednotifikasispwidget/generated/GeneratedGroup6Widget3.dart';

/* Frame Notifikasi SP
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNotifikasiSPWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 414.0,
              height: 896.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 144.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 560.0,
                      child: GeneratedFrame48Widget1(),
                    ),
                    Positioned(
                      left: 43.0,
                      top: 215.0,
                      right: null,
                      bottom: null,
                      width: 328.0,
                      height: 541.0,
                      child: GeneratedFrame49Widget1(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 832.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 64.0,
              child: GeneratedFrame5Widget6(),
            ),
            Positioned(
              left: 0.0,
              top: 804.0,
              right: null,
              bottom: null,
              width: 0.0,
              height: 0.0,
              child: GeneratedGroup62Widget3(),
            ),
            Positioned(
              left: 0.0,
              top: 112.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 31.0,
              child: GeneratedGroup20Widget2(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 112.0,
              child: GeneratedGroup6Widget3(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 896.0,
              child: GeneratedFrame47Widget(),
            ),
            Positioned(
              left: 56.0,
              top: 286.0,
              right: null,
              bottom: null,
              width: 303.0,
              height: 324.0,
              child: GeneratedFrame51Widget(),
            )
          ]),
    ));
  }
}
