import 'package:flutter/material.dart';
import 'package:flutterapp/ui_designapp/generatedanekausahawidget13/generated/GeneratedFrame8Widget9.dart';
import 'package:flutterapp/ui_designapp/generatedanekausahawidget13/generated/GeneratedFrame12Widget1.dart';
import 'package:flutterapp/ui_designapp/generatedanekausahawidget13/generated/GeneratedGroup6Widget13.dart';
import 'package:flutterapp/ui_designapp/generatedanekausahawidget13/generated/GeneratedGroup62Widget13.dart';
import 'package:flutterapp/ui_designapp/generatedanekausahawidget13/generated/GeneratedGroup9Widget1.dart';
import 'package:flutterapp/ui_designapp/generatedanekausahawidget13/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/ui_designapp/generatedanekausahawidget13/generated/GeneratedFrame5Widget24.dart';
import 'package:flutterapp/ui_designapp/generatedanekausahawidget13/generated/GeneratedGroup8Widget1.dart';
import 'package:flutterapp/ui_designapp/generatedanekausahawidget13/generated/GeneratedGroup7Widget1.dart';

/* Frame Aneka Usaha
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAnekaUsahaWidget13 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1225.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 414.0,
                            height: 1225.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 168.0,
                                    right: null,
                                    bottom: null,
                                    width: 382.0,
                                    height: 240.0,
                                    child: GeneratedGroup7Widget1(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 422.0,
                                    right: null,
                                    bottom: null,
                                    width: 382.0,
                                    height: 240.0,
                                    child: GeneratedGroup8Widget1(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 676.0,
                                    right: null,
                                    bottom: null,
                                    width: 382.0,
                                    height: 240.0,
                                    child: GeneratedGroup9Widget1(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 930.0,
                                    right: null,
                                    bottom: null,
                                    width: 382.0,
                                    height: 240.0,
                                    child: GeneratedGroup10Widget(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 178.0,
                                    right: null,
                                    bottom: null,
                                    width: 382.0,
                                    height: 42.0,
                                    child: GeneratedFrame8Widget9(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 832.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 64.0,
              child: GeneratedFrame5Widget24(),
            ),
            Positioned(
              left: 0.0,
              top: 805.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 92.0,
              child: GeneratedGroup62Widget13(),
            ),
            Positioned(
              left: 0.0,
              top: 112.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 48.0,
              child: GeneratedFrame12Widget1(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 112.0,
              child: GeneratedGroup6Widget13(),
            )
          ]),
    ));
  }
}
