import 'package:flutter/material.dart';
import 'package:flutterapp/ui_designapp/generatedgambarwisatawidget/generated/Generated6a7eb81dlabuanbajoWidget1.dart';
import 'package:flutterapp/ui_designapp/generatedgambarwisatawidget/generated/GeneratedRaja_Ampat_Mutiara_Indah_di_Timur_IndonesiaWidget1.dart';
import 'package:flutterapp/ui_designapp/generatedgambarwisatawidget/generated/GeneratedUntitled7Widget1.dart';
import 'package:flutterapp/ui_designapp/generatedgambarwisatawidget/generated/GeneratedTelagawarnadieng1Widget1.dart';
import 'package:flutterapp/ui_designapp/generatedgambarwisatawidget/generated/Generated162455385768440566380ed85760f77496a3434b9f4cf1Widget1.dart';
import 'package:flutterapp/ui_designapp/generatedgambarwisatawidget/generated/GeneratedKawahratutangkubanparahuWidget1.dart';
import 'package:flutterapp/ui_designapp/generatedgambarwisatawidget/generated/GeneratedMmmmWidget2.dart';
import 'package:flutterapp/ui_designapp/generatedgambarwisatawidget/generated/GeneratedF4024c571e5e09ce5e4049bc181500b1borobudurtempleWidget1.dart';

/* Group Gambar Wisata
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGambarWisataWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: Container(
        width: 0.0,
        height: 0.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 2616.0,
                right: null,
                bottom: null,
                width: 600.0,
                height: 400.0,
                child: Generated6a7eb81dlabuanbajoWidget1(),
              ),
              Positioned(
                left: 1538.0,
                top: 2592.0,
                right: null,
                bottom: null,
                width: 1024.0,
                height: 683.0,
                child: GeneratedTelagawarnadieng1Widget1(),
              ),
              Positioned(
                left: 62.0,
                top: 889.0,
                right: null,
                bottom: null,
                width: 2500.0,
                height: 1668.0,
                child:
                    GeneratedRaja_Ampat_Mutiara_Indah_di_Timur_IndonesiaWidget1(),
              ),
              Positioned(
                left: 2727.0,
                top: 1898.0,
                right: null,
                bottom: null,
                width: 1059.0,
                height: 659.0,
                child: GeneratedMmmmWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 637.0,
                height: 642.0,
                child: GeneratedUntitled7Widget1(),
              ),
              Positioned(
                left: 1117.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1200.0,
                height: 800.0,
                child:
                    GeneratedF4024c571e5e09ce5e4049bc181500b1borobudurtempleWidget1(),
              ),
              Positioned(
                left: 3343.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 1280.0,
                height: 720.0,
                child: GeneratedKawahratutangkubanparahuWidget1(),
              ),
              Positioned(
                left: 2757.0,
                top: 889.0,
                right: null,
                bottom: null,
                width: 1000.0,
                height: 688.0,
                child:
                    Generated162455385768440566380ed85760f77496a3434b9f4cf1Widget1(),
              )
            ]),
      ),
    ));
  }
}
