import 'package:flutter/material.dart';

/* Rectangle WhatsApp Image 2021-12-01 at 20.23 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWhatsAppImage20211201at20231Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: Container(
        width: 415.0,
        height: 1600.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Image.asset(
            "assets/images/32c094d0a3418647192702cf6a012208d128ac35.png",
            color: null,
            fit: BoxFit.cover,
            width: 415.0,
            height: 1600.0,
            colorBlendMode: BlendMode.dstATop,
          ),
        ),
      ),
    ));
  }
}
