import 'package:flutter/material.dart';
import 'package:flutterapp/ui_designapp/generatediconwidget/generated/GeneratedFrameWidget513.dart';
import 'package:flutterapp/ui_designapp/generatediconwidget/generated/GeneratedIconWidget1.dart';
import 'package:flutterapp/ui_designapp/generatediconwidget/generated/GeneratedFrameWidget514.dart';
import 'package:flutterapp/ui_designapp/generatediconwidget/generated/GeneratedFrameWidget515.dart';

/* Group Icon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIconWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: Container(
        width: 0.0,
        height: 0.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 30.0,
                child: GeneratedIconWidget1(),
              ),
              Positioned(
                left: 52.0,
                top: 71.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedFrameWidget513(),
              ),
              Positioned(
                left: 0.0,
                top: 71.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedFrameWidget514(),
              ),
              Positioned(
                left: 104.0,
                top: 71.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedFrameWidget515(),
              )
            ]),
      ),
    ));
  }
}
