import 'package:flutter/material.dart';
import 'package:flutterapp/ui_designapp/generatednotifkeranjangwidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/ui_designapp/generatednotifkeranjangwidget/generated/GeneratedFrame6Widget.dart';
import 'package:flutterapp/ui_designapp/generatednotifkeranjangwidget/generated/GeneratedGroup63Widget1.dart';
import 'package:flutterapp/ui_designapp/generatednotifkeranjangwidget/generated/GeneratedGroup62Widget.dart';
import 'package:flutterapp/ui_designapp/generatednotifkeranjangwidget/generated/GeneratedFrame8Widget.dart';
import 'package:flutterapp/ui_designapp/generatednotifkeranjangwidget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/ui_designapp/generatednotifkeranjangwidget/generated/GeneratedFrame14Widget.dart';
import 'package:flutterapp/ui_designapp/generatednotifkeranjangwidget/generated/GeneratedFrame27Widget.dart';
import 'package:flutterapp/ui_designapp/generatednotifkeranjangwidget/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/ui_designapp/generatednotifkeranjangwidget/generated/GeneratedFrame5Widget.dart';
import 'package:flutterapp/ui_designapp/generatednotifkeranjangwidget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/ui_designapp/generatednotifkeranjangwidget/generated/GeneratedFrame13Widget.dart';

/* Frame Notif keranjang
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNotifkeranjangWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1201.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 414.0,
                            height: 1201.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 400.0,
                                    right: null,
                                    bottom: null,
                                    width: 382.0,
                                    height: 42.0,
                                    child: GeneratedFrame8Widget(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 393.0,
                                    right: null,
                                    bottom: null,
                                    width: 381.0,
                                    height: 240.0,
                                    child: GeneratedGroup7Widget(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 647.0,
                                    right: null,
                                    bottom: null,
                                    width: 381.0,
                                    height: 240.0,
                                    child: GeneratedGroup8Widget(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 901.0,
                                    right: null,
                                    bottom: null,
                                    width: 381.0,
                                    height: 240.0,
                                    child: GeneratedGroup9Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 378.0,
                                    right: null,
                                    bottom: null,
                                    width: 414.0,
                                    height: 823.0,
                                    child: GeneratedFrame27Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 112.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 266.0,
              child: GeneratedFrame14Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 832.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 64.0,
              child: GeneratedFrame5Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 804.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 92.0,
              child: GeneratedGroup62Widget(),
            ),
            Positioned(
              left: 16.0,
              top: 288.0,
              right: null,
              bottom: null,
              width: 382.0,
              height: 86.0,
              child: GeneratedFrame13Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 0.0,
              height: 0.0,
              child: GeneratedGroup6Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 112.0,
              child: GeneratedGroup63Widget1(),
            ),
            Positioned(
              left: 16.0,
              top: 120.0,
              right: null,
              bottom: null,
              width: 382.0,
              height: 164.0,
              child: GeneratedFrame6Widget(),
            )
          ]),
    ));
  }
}
