import 'package:flutter/material.dart';
import 'package:flutterapp/ui_designapp/generatedgrafikwidget9/generated/GeneratedGroup6Widget9.dart';
import 'package:flutterapp/ui_designapp/generatedgrafikwidget9/generated/GeneratedFrame29Widget.dart';
import 'package:flutterapp/ui_designapp/generatedgrafikwidget9/generated/GeneratedFrame52Widget.dart';
import 'package:flutterapp/ui_designapp/generatedgrafikwidget9/generated/GeneratedFrame5Widget16.dart';
import 'package:flutterapp/ui_designapp/generatedgrafikwidget9/generated/GeneratedFrame8Widget3.dart';
import 'package:flutterapp/ui_designapp/generatedgrafikwidget9/generated/GeneratedFrame12Widget.dart';
import 'package:flutterapp/ui_designapp/generatedgrafikwidget9/generated/GeneratedGroup62Widget9.dart';
import 'package:flutterapp/ui_designapp/generatedgrafikwidget9/generated/GeneratedAsasa1Widget.dart';

/* Frame Grafik
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGrafikWidget9 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 414.0,
              height: 896.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 178.0,
                      right: null,
                      bottom: null,
                      width: 382.0,
                      height: 42.0,
                      child: GeneratedFrame8Widget3(),
                    ),
                    Positioned(
                      left: -2.0,
                      top: 323.0,
                      right: null,
                      bottom: null,
                      width: 415.0,
                      height: 396.0,
                      child: GeneratedAsasa1Widget(),
                    ),
                    Positioned(
                      left: 19.0,
                      top: 338.0,
                      right: null,
                      bottom: null,
                      width: 379.0,
                      height: 451.0,
                      child: GeneratedFrame52Widget(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 832.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 64.0,
              child: GeneratedFrame5Widget16(),
            ),
            Positioned(
              left: 0.0,
              top: 805.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 92.0,
              child: GeneratedGroup62Widget9(),
            ),
            Positioned(
              left: 0.0,
              top: 112.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 48.0,
              child: GeneratedFrame12Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 160.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 145.0,
              child: GeneratedFrame29Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 112.0,
              child: GeneratedGroup6Widget9(),
            )
          ]),
    ));
  }
}
