import 'package:flutter/material.dart';

/* Rectangle Screenshot_20211202-122047_MySiskop Adis 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreenshot_20211202122047_MySiskopAdis1Widget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: Container(
        width: 486.4864807128906,
        height: 1000.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Image.asset(
            "assets/images/c1d53f9009d1596c3282ab03fe8f7d4414e56d98.png",
            color: null,
            fit: BoxFit.cover,
            width: 486.4864807128906,
            height: 1000.0,
            colorBlendMode: BlendMode.dstATop,
          ),
        ),
      ),
    ));
  }
}
