import 'package:flutter/material.dart';
import 'package:flutterapp/ui_designapp/generatedtypographywidget/generated/GeneratedHeading2Widget.dart';
import 'package:flutterapp/ui_designapp/generatedtypographywidget/generated/GeneratedHeading1Widget.dart';
import 'package:flutterapp/ui_designapp/generatedtypographywidget/generated/GeneratedTextBodyWidget.dart';
import 'package:flutterapp/ui_designapp/generatedtypographywidget/generated/GeneratedTypographyWidget1.dart';

/* Group Typography
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTypographyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: Container(
        width: 0.0,
        height: 0.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 30.0,
                child: GeneratedTypographyWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 44.0,
                child: GeneratedHeading1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 30.0,
                child: GeneratedHeading2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 17.0,
                child: GeneratedTextBodyWidget(),
              )
            ]),
      ),
    ));
  }
}
