import 'package:flutter/material.dart';
import 'package:flutterapp/ui_designapp/generatednotifikasicheckoutwidget/generated/GeneratedFrame5Widget15.dart';
import 'package:flutterapp/ui_designapp/generatednotifikasicheckoutwidget/generated/GeneratedFrame23Widget1.dart';
import 'package:flutterapp/ui_designapp/generatednotifikasicheckoutwidget/generated/GeneratedGroup6Widget8.dart';
import 'package:flutterapp/ui_designapp/generatednotifikasicheckoutwidget/generated/GeneratedFrame21Widget1.dart';
import 'package:flutterapp/ui_designapp/generatednotifikasicheckoutwidget/generated/GeneratedFrame25Widget1.dart';
import 'package:flutterapp/ui_designapp/generatednotifikasicheckoutwidget/generated/GeneratedFrame8Widget2.dart';
import 'package:flutterapp/ui_designapp/generatednotifikasicheckoutwidget/generated/GeneratedFrame22Widget7.dart';
import 'package:flutterapp/ui_designapp/generatednotifikasicheckoutwidget/generated/GeneratedGroup62Widget8.dart';
import 'package:flutterapp/ui_designapp/generatednotifikasicheckoutwidget/generated/GeneratedFrame24Widget1.dart';
import 'package:flutterapp/ui_designapp/generatednotifikasicheckoutwidget/generated/GeneratedFrame47Widget1.dart';
import 'package:flutterapp/ui_designapp/generatednotifikasicheckoutwidget/generated/GeneratedFrame45Widget.dart';
import 'package:flutterapp/ui_designapp/generatednotifikasicheckoutwidget/generated/GeneratedGroup20Widget6.dart';

/* Frame Notifikasi CheckOut
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNotifikasiCheckOutWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 414.0,
              height: 896.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 400.0,
                      right: null,
                      bottom: null,
                      width: 382.0,
                      height: 42.0,
                      child: GeneratedFrame8Widget2(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 148.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 100.0,
                      child: GeneratedFrame21Widget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 254.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 100.0,
                      child: GeneratedFrame22Widget7(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 360.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 100.0,
                      child: GeneratedFrame23Widget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 466.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 100.0,
                      child: GeneratedFrame24Widget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 572.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 100.0,
                      child: GeneratedFrame25Widget1(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 832.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 64.0,
              child: GeneratedFrame5Widget15(),
            ),
            Positioned(
              left: 0.0,
              top: 804.0,
              right: null,
              bottom: null,
              width: 0.0,
              height: 0.0,
              child: GeneratedGroup62Widget8(),
            ),
            Positioned(
              left: 0.0,
              top: 112.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 30.0,
              child: GeneratedGroup20Widget6(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 112.0,
              child: GeneratedGroup6Widget8(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 896.0,
              child: GeneratedFrame47Widget1(),
            ),
            Positioned(
              left: 56.0,
              top: 283.0,
              right: null,
              bottom: null,
              width: 303.0,
              height: 324.0,
              child: GeneratedFrame45Widget(),
            )
          ]),
    ));
  }
}
