import 'package:flutter/material.dart';
import 'package:flutterapp/ui_designapp/generatedsimulasipinjamanuspwidget/generated/GeneratedGroup20Widget3.dart';
import 'package:flutterapp/ui_designapp/generatedsimulasipinjamanuspwidget/generated/GeneratedFrame48Widget2.dart';
import 'package:flutterapp/ui_designapp/generatedsimulasipinjamanuspwidget/generated/GeneratedGroup62Widget4.dart';
import 'package:flutterapp/ui_designapp/generatedsimulasipinjamanuspwidget/generated/GeneratedFrame5Widget7.dart';
import 'package:flutterapp/ui_designapp/generatedsimulasipinjamanuspwidget/generated/GeneratedGroup6Widget4.dart';

/* Frame Simulasi pinjaman (USP)
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSimulasipinjamanUSPWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 414.0,
              height: 896.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 144.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 560.0,
                      child: GeneratedFrame48Widget2(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 832.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 64.0,
              child: GeneratedFrame5Widget7(),
            ),
            Positioned(
              left: 0.0,
              top: 804.0,
              right: null,
              bottom: null,
              width: 0.0,
              height: 0.0,
              child: GeneratedGroup62Widget4(),
            ),
            Positioned(
              left: 0.0,
              top: 112.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 31.0,
              child: GeneratedGroup20Widget3(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 112.0,
              child: GeneratedGroup6Widget4(),
            )
          ]),
    ));
  }
}
