import 'package:flutter/material.dart';
import 'package:flutterapp/ui_designapp/generatedtabungansukarelawidget/generated/GeneratedFrame44Widget.dart';
import 'package:flutterapp/ui_designapp/generatedtabungansukarelawidget/generated/GeneratedFrame38Widget.dart';
import 'package:flutterapp/ui_designapp/generatedtabungansukarelawidget/generated/GeneratedGroup6Widget10.dart';
import 'package:flutterapp/ui_designapp/generatedtabungansukarelawidget/generated/GeneratedFrame39Widget.dart';
import 'package:flutterapp/ui_designapp/generatedtabungansukarelawidget/generated/GeneratedFrame37Widget.dart';
import 'package:flutterapp/ui_designapp/generatedtabungansukarelawidget/generated/GeneratedFrame42Widget.dart';
import 'package:flutterapp/ui_designapp/generatedtabungansukarelawidget/generated/GeneratedFrame36Widget.dart';
import 'package:flutterapp/ui_designapp/generatedtabungansukarelawidget/generated/GeneratedFrame40Widget.dart';
import 'package:flutterapp/ui_designapp/generatedtabungansukarelawidget/generated/GeneratedFrame31Widget.dart';
import 'package:flutterapp/ui_designapp/generatedtabungansukarelawidget/generated/GeneratedGroup62Widget10.dart';
import 'package:flutterapp/ui_designapp/generatedtabungansukarelawidget/generated/GeneratedFrame8Widget4.dart';
import 'package:flutterapp/ui_designapp/generatedtabungansukarelawidget/generated/GeneratedFrame32Widget.dart';
import 'package:flutterapp/ui_designapp/generatedtabungansukarelawidget/generated/GeneratedFrame33Widget.dart';
import 'package:flutterapp/ui_designapp/generatedtabungansukarelawidget/generated/GeneratedFrame35Widget.dart';
import 'package:flutterapp/ui_designapp/generatedtabungansukarelawidget/generated/GeneratedFrame34Widget.dart';
import 'package:flutterapp/ui_designapp/generatedtabungansukarelawidget/generated/GeneratedFrame41Widget.dart';
import 'package:flutterapp/ui_designapp/generatedtabungansukarelawidget/generated/GeneratedFrame43Widget.dart';
import 'package:flutterapp/ui_designapp/generatedtabungansukarelawidget/generated/GeneratedFrame30Widget.dart';
import 'package:flutterapp/ui_designapp/generatedtabungansukarelawidget/generated/GeneratedFrame5Widget18.dart';

/* Frame Tabungan sukarela
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTabungansukarelaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1060.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 414.0,
                            height: 1060.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 178.0,
                                    right: null,
                                    bottom: null,
                                    width: 382.0,
                                    height: 42.0,
                                    child: GeneratedFrame8Widget4(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 462.0,
                                    right: null,
                                    bottom: null,
                                    width: 414.0,
                                    height: 24.0,
                                    child: GeneratedFrame34Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 669.0,
                                    right: null,
                                    bottom: null,
                                    width: 414.0,
                                    height: 24.0,
                                    child: GeneratedFrame42Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 997.0,
                                    right: null,
                                    bottom: null,
                                    width: 414.0,
                                    height: 61.0,
                                    child: GeneratedFrame44Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 936.0,
                                    right: null,
                                    bottom: null,
                                    width: 414.0,
                                    height: 61.0,
                                    child: GeneratedFrame43Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 875.0,
                                    right: null,
                                    bottom: null,
                                    width: 414.0,
                                    height: 61.0,
                                    child: GeneratedFrame41Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 814.0,
                                    right: null,
                                    bottom: null,
                                    width: 414.0,
                                    height: 61.0,
                                    child: GeneratedFrame40Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 753.0,
                                    right: null,
                                    bottom: null,
                                    width: 414.0,
                                    height: 61.0,
                                    child: GeneratedFrame39Widget(),
                                  ),
                                  Positioned(
                                    left: -1.0,
                                    top: 692.0,
                                    right: null,
                                    bottom: null,
                                    width: 415.0,
                                    height: 61.0,
                                    child: GeneratedFrame38Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 608.0,
                                    right: null,
                                    bottom: null,
                                    width: 414.0,
                                    height: 61.0,
                                    child: GeneratedFrame37Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 547.0,
                                    right: null,
                                    bottom: null,
                                    width: 414.0,
                                    height: 61.0,
                                    child: GeneratedFrame36Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 486.0,
                                    right: null,
                                    bottom: null,
                                    width: 414.0,
                                    height: 61.0,
                                    child: GeneratedFrame35Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 344.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 50.0,
              child: GeneratedFrame32Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 394.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 68.0,
              child: GeneratedFrame33Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 832.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 64.0,
              child: GeneratedFrame5Widget18(),
            ),
            Positioned(
              left: 0.0,
              top: 804.0,
              right: null,
              bottom: null,
              width: 0.0,
              height: 0.0,
              child: GeneratedGroup62Widget10(),
            ),
            Positioned(
              left: 0.0,
              top: 112.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 232.0,
              child: GeneratedFrame31Widget(),
            ),
            Positioned(
              left: 16.0,
              top: 123.0,
              right: null,
              bottom: null,
              width: 382.0,
              height: 206.0,
              child: GeneratedFrame30Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 112.0,
              child: GeneratedGroup6Widget10(),
            )
          ]),
    ));
  }
}
