import 'package:flutter/material.dart';
import 'package:flutterapp/ui_designapp/generatedstylecoloringwidget/generated/GeneratedEllipse11Widget.dart';
import 'package:flutterapp/ui_designapp/generatedstylecoloringwidget/generated/GeneratedEllipse9Widget.dart';
import 'package:flutterapp/ui_designapp/generatedstylecoloringwidget/generated/GeneratedEllipse8Widget.dart';
import 'package:flutterapp/ui_designapp/generatedstylecoloringwidget/generated/GeneratedStyleColorWidget.dart';
import 'package:flutterapp/ui_designapp/generatedstylecoloringwidget/generated/GeneratedEllipse12Widget.dart';
import 'package:flutterapp/ui_designapp/generatedstylecoloringwidget/generated/GeneratedEllipse10Widget.dart';
import 'package:flutterapp/ui_designapp/generatedstylecoloringwidget/generated/GeneratedEllipse13Widget1.dart';

/* Group Style Coloring
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStyleColoringWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: Container(
        width: 0.0,
        height: 0.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedEllipse8Widget(),
              ),
              Positioned(
                left: 258.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedEllipse11Widget(),
              ),
              Positioned(
                left: 344.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedEllipse12Widget(),
              ),
              Positioned(
                left: 172.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedEllipse10Widget(),
              ),
              Positioned(
                left: 430.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedEllipse13Widget1(),
              ),
              Positioned(
                left: 86.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedEllipse9Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 30.0,
                child: GeneratedStyleColorWidget(),
              )
            ]),
      ),
    ));
  }
}
